### Python

In [137]:
# lists
ls = [1,2,12,15,6,2,"A",[1,2,3],True]

In [138]:
ls[::-1]

[True, [1, 2, 3], 'A', 2, 6, 15, 12, 2, 1]

#### lists
- Adding a new elemts:
    - Append
    - Insert
    - Extend

In [139]:
ls

[1, 2, 12, 15, 6, 2, 'A', [1, 2, 3], True]

In [140]:
ls.append('B')
ls

[1, 2, 12, 15, 6, 2, 'A', [1, 2, 3], True, 'B']

In [141]:
ls.insert(1,'in')
ls

[1, 'in', 2, 12, 15, 6, 2, 'A', [1, 2, 3], True, 'B']

In [142]:
ls.insert(-1,[1,2,3])
ls

[1, 'in', 2, 12, 15, 6, 2, 'A', [1, 2, 3], True, [1, 2, 3], 'B']

In [143]:
ls1 = ['J','K','L']
ls.extend(ls1)

In [144]:
ls

[1, 'in', 2, 12, 15, 6, 2, 'A', [1, 2, 3], True, [1, 2, 3], 'B', 'J', 'K', 'L']

In [145]:
#ls.extend(['python','exam','test'])
#ls

#### lists
- removing
    - pop
    - remove
    - del

In [146]:
ls

[1, 'in', 2, 12, 15, 6, 2, 'A', [1, 2, 3], True, [1, 2, 3], 'B', 'J', 'K', 'L']

In [147]:
ls.pop()

'L'

In [148]:
ls

[1, 'in', 2, 12, 15, 6, 2, 'A', [1, 2, 3], True, [1, 2, 3], 'B', 'J', 'K']

In [149]:
ls.pop(0)

1

In [150]:
ls

['in', 2, 12, 15, 6, 2, 'A', [1, 2, 3], True, [1, 2, 3], 'B', 'J', 'K']

In [152]:
ls.remove(12)

In [153]:
ls

['in', 2, 15, 6, 2, 'A', [1, 2, 3], True, [1, 2, 3], 'B', 'J', 'K']

In [154]:
del ls[-4:-1]
ls

['in', 2, 15, 6, 2, 'A', [1, 2, 3], True, 'K']

In [155]:
ls

['in', 2, 15, 6, 2, 'A', [1, 2, 3], True, 'K']

In [156]:
ls[-3].extend(['A','B'])
ls

['in', 2, 15, 6, 2, 'A', [1, 2, 3, 'A', 'B'], True, 'K']

### Dictionaries
    - keys
    - values
    - items

In [31]:
d = {"a":"apple","b":"ball","c":'cat',"d":"dog"}

In [32]:
d.keys()

dict_keys(['a', 'b', 'c', 'd'])

In [162]:
def getList(dict):
    return list(dict.keys())

ls1= getList(d)
print(ls1)
ls1[::-1]

print(ls1)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd']


In [33]:
d.values()

dict_values(['apple', 'ball', 'cat', 'dog'])

In [34]:
d.items()

dict_items([('a', 'apple'), ('b', 'ball'), ('c', 'cat'), ('d', 'dog')])

In [164]:
def getList(dict):
    return list(dict.items())

ls2= getList(d)
ls2[::-1]
ls2

[('a', 'apple'), ('b', 'ball'), ('c', 'cat'), ('d', 'dog')]

In [196]:
d1 ={'a':1,'b':2,'c':3,'d':4}

In [201]:
{k:v for k,v in d1.items() if v%2==0}

{'b': 2, 'd': 4}

In [165]:
s = 'Exam is going to be good'

In [41]:
#s[::-1]

'doog eb ot gniog si maxE'

In [169]:
s1 = s.split(' ')
s1

['Exam', 'is', 'going', 'to', 'be', 'good']

In [168]:
s1[::-1]

['good', 'be', 'to', 'going', 'is', 'Exam']

In [ ]:
# single line for above code
#s.split(' ')[::-1]

In [185]:
w =[w[::-1] for w in s.split(' ')]
w

['maxE', 'si', 'gniog', 'ot', 'eb', 'doog']

In [186]:
' '.join(w)

'maxE si gniog ot eb doog'

In [178]:
#single line of code for above code
' '.join([w[::-1] for w in s.split(' ')])

'maxE si gniog ot eb doog'

In [192]:
ls =['3_xy.png','04_xy.txt','2_z.png','04_xy.txt']

In [195]:
ls.sort(key=lambda x:int(x.split('_')[0]))
ls

['2_z.png', '3_xy.png', '04_xy.txt', '04_xy.txt']

In [43]:
sorted(ls,key= lambda x:int(x.split('_')[0]))

['2_z.png', '3_xy.png', '04_xy.txt', '04_xy.txt']

#### map
- map a function to each of the list

In [206]:
ls = [2,3,4,5,6]
list(map(lambda x:x*x,ls))

[4, 9, 16, 25, 36]

In [207]:
d2 = {0:1,1:2}
list(map(lambda x:x*x,d2.values()))

[1, 4]

#### Filter 
    - filter those elements that satisfies the condition

In [14]:
ls = [2,3,4,5,6]
list(filter(lambda x:x%2==0,ls))

[2, 4, 6]

In [208]:
list(filter(lambda x:x%2!=0 ,ls))

[3, 5]

In [15]:
[item for item in ls if item%2==0]

[2, 4, 6]

In [54]:
4%2==0

True

In [11]:
from functools import reduce

ls = [9,10,14,5,6]
reduce(lambda a,b:a if a<b else b,ls)


5

In [12]:
ls = [9,10,14,5,6]
reduce(lambda a,b:a if a>b else b, ls)

14

In [65]:
reduce(lambda a,b:a+b,ls)

44

#### Numpy

In [66]:
import numpy as np

In [67]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.fliplr(a)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [71]:
np.flipud(a)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [212]:
a = np.zeros((3,3),dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [73]:
a.fill(5)
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [74]:
np.fill_diagonal(a,1)
a

array([[1, 5, 5],
       [5, 1, 5],
       [5, 5, 1]])

In [75]:
np.fill_diagonal(np.flipud(a),1)
a

array([[1, 5, 1],
       [5, 1, 5],
       [1, 5, 1]])

In [76]:
np.flipud(a)

array([[1, 5, 1],
       [5, 1, 5],
       [1, 5, 1]])

In [100]:
np.pad(a,pad_width=1,constant_values = 0)

array([[0, 0, 0, 0, 0],
       [0, 1, 5, 1, 0],
       [0, 5, 1, 5, 0],
       [0, 1, 5, 1, 0],
       [0, 0, 0, 0, 0]])

In [79]:
import pandas as pd

In [102]:
data = {'Country': ['Belgium',  'India',  'Brazil'],
        'Population': [11190846, 1303171035, 207847528]}
df1 = pd.DataFrame(data,columns=['Country',  'Population'])
df1

Country  Population
0  Belgium    11190846
1    India  1303171035
2   Brazil   207847528

In [81]:
data2 = {'Capital': ['Brussels',  'New Delhi',  'Brasilia']}
df2 = pd.DataFrame(data2,columns=['Capital'])
df2

Capital
0   Brussels
1  New Delhi
2   Brasilia

In [82]:
pd.concat([df1,df2],axis=1)

Country  Population    Capital
0  Belgium    11190846   Brussels
1    India  1303171035  New Delhi
2   Brazil   207847528   Brasilia

In [5]:
import time

ReportGenrationDates = {'P1':'26/01/2020','P2':'24/01/2020','P4':'27/02/2019', 'P3':'28/02/2020'}
PatientsReports = ['P1.png', 'P2.png', 'P3.png', 'P4.png']

ReportGenrationDates = {F'{k}.png':time.strptime(v,'%d/%m/%Y') for k,v in ReportGenrationDates.items()}

PatientsReports.sort(key=lambda x:ReportGenrationDates[x],reverse=False)
PatientsReports

['P4.png', 'P2.png', 'P1.png', 'P3.png']

In [84]:
l1 = ["manish", 'sumit','rajesh','nekanti']
l2 = ["kumar", 'gupta','katreddy','shivaramakrishna','test']

from itertools import product
list(product(l1,l2))

[('manish', 'kumar'),
 ('manish', 'gupta'),
 ('manish', 'katreddy'),
 ('manish', 'shivaramakrishna'),
 ('manish', 'test'),
 ('sumit', 'kumar'),
 ('sumit', 'gupta'),
 ('sumit', 'katreddy'),
 ('sumit', 'shivaramakrishna'),
 ('sumit', 'test'),
 ('rajesh', 'kumar'),
 ('rajesh', 'gupta'),
 ('rajesh', 'katreddy'),
 ('rajesh', 'shivaramakrishna'),
 ('rajesh', 'test'),
 ('nekanti', 'kumar'),
 ('nekanti', 'gupta'),
 ('nekanti', 'katreddy'),
 ('nekanti', 'shivaramakrishna'),
 ('nekanti', 'test')]

In [85]:
list(zip(l1,l2))

[('manish', 'kumar'),
 ('sumit', 'gupta'),
 ('rajesh', 'katreddy'),
 ('nekanti', 'shivaramakrishna')]

In [86]:
[' '.join(name) for name in zip(l1,l2)]

['manish kumar', 'sumit gupta', 'rajesh katreddy', 'nekanti shivaramakrishna']

In [214]:
for i in range(5):
    print(str(i)*i)


1
22
333
4444


In [218]:
n=4
for i in range(5)[::-1]:
    print(' '*(n-i)+str(i)*i)

4444
 333
  22
   1
    


In [221]:
n=4
for i in range(n)[::-1]:
    print(' '*(n-i)+'*'*(i*2+1))

 *******
  *****
   ***
    *


In [220]:
n=7
for i in range(n)[::-1]:
    print(' '*(n-i)+'*'*((i*2)+1))
# *****
#  ***
#   *

 *************
  ***********
   *********
    *******
     *****
      ***
       *


In [9]:
import pandas as pd
data = {'name': ['nick', 'david', 'joe', 'ross'],
        'age': ['5', '10', '7', '6']} 
new = pd.DataFrame(data, columns=['name'])
new

name
0   nick
1  david
2    joe
3   ross

In [19]:
input_list = ["a12345","a1234","123","124","125","12216"]
ls = []
for item in input_list:
    if item.startswith("a") & (len(item)==6):
        ls.append(item)
        
print(ls)

['a12345']
